// Generated by Wrangler on Mon May 20 2024 19:32:32 GMT-0500 (Central Daylight Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
    DATABASE: D1Database; 
}