// Generated by Wrangler on Tue May 21 2024 15:11:47 GMT-0500 (Central Daylight Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
	NEXTAUTH_SECRET: string;
	R2_ENDPOINT: string;
	R2_ACCESS_ID: string;
	R2_SECRET_KEY: string;
	R2_BUCKET_NAME: string;
	STORAGE: R2Bucket;
	DATABASE: D1Database;
}
