// Generated by Wrangler on Wed Sep 04 2024 11:25:36 GMT-0700 (Mountain Standard Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	DATABASE: D1Database;
}
