name = "cloudflare-saas-stack"
compatibility_date = "2024-09-03"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"
send_metrics = false

[placement]
mode = "smart"

[[d1_databases]]
binding = "DATABASE"
database_name = "cloudfare-test-stack"
database_id = "3a93b7d0-c4f5-460e-a9a8-1ae9f4157cfa"
